#command to run cloud build: gcloud builds submit --config=cloudbuild.yaml
#check images: gcloud artifacts docker images list
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/dataflow/branching:latest', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'dataflow', 'flex-template', 'build', 'gs://toanbui1991-dataflow-templates/branching.json',
      '--image', 'gcr.io/$PROJECT_ID/dataflow/branching:latest', '--sdk-language', 'PYTHON', '--metadata-file',
      'metadata.json' ]


images:
  - 'gcr.io/${PROJECT_ID}/dataflow/branching:latest'