version: "3.7"
services:
  db:
    build: .
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=VeryComplicatedPassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=VeryComplciatedPassword
  wordpress:
    build: .
    container_name: wordpress_new
    ports:
      - 80:80